In [7]:
import numpy as np
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(type(array_float))
print(array_float.dtype)

<class 'numpy.ndarray'>
float64


In [9]:
one_array = np.ones((3,2))
zero_array = np.zeros((3,2))
print(one_array.astype('int32'))
print(zero_array.astype('int32'))

[[1 1]
 [1 1]
 [1 1]]
[[0 0]
 [0 0]
 [0 0]]


In [3]:
import numpy as np
from numpy.linalg import svd

A = np.array([[1, 0, 0],[0, 2, 1],[0, 1, 1],[4, 0, 1]])
U, S, VT = svd(A)

In [4]:
U

array([[-0.22601997, -0.07296014,  0.46510113, -0.85280287],
       [-0.09137373,  0.84644465,  0.47929924,  0.21320072],
       [-0.07702886,  0.51707108, -0.73816385, -0.42640143],
       [-0.96676387, -0.10414306, -0.09522241,  0.21320072]])

In [7]:
np.diag(S, 1)[:, 1:]

array([[4.25550856, 0.        , 0.        ],
       [0.        , 2.59028692, 0.        ],
       [0.        , 0.        , 0.42551218],
       [0.        , 0.        , 0.        ]])

In [6]:
VT

array([[-0.96182991, -0.06104472, -0.26675224],
       [-0.1889877 ,  0.85317204,  0.48619041],
       [ 0.1979062 ,  0.51804538, -0.83214309]])