# 데이터 인코딩
## Label encoding
카테고리 피터를 코드형 숫자 값으로 변환하는 것

In [3]:
#데이터 인코(레이블 인코딩)
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)
print('인코딩 클래스:', encoder.classes_)

인코딩 변환값: [0 1 2 3]
인코딩 클래스: ['TV' '냉장고' '전자레인지' '컴퓨터']


레이블 인코딩은 분류 값이 크면 알고리즘에서 가중치가 더 부가되서 생기는 문제점이 있다.<br>
그래서 문제점을 해결한 <br>
## One-hot encoding
분류 할 대상은 1 나머지는 모두 0의 값으로 표현!

In [4]:
# one-hot encoding
from sklearn.preprocessing import OneHotEncoder
import numpy as np

labels = labels.reshape(-1,1)

#one-hot encoding imply
oh_encoder = OneHotEncoder(categories='auto')
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print(oh_labels.toarray())
print(oh_labels.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


# feature scaling 
## Standardization
\begin{equation*}
\mathbf{x}_i\_new\ = \frac{\mathbf{x}_i-mean(x)}{stdev(x)}
\end{equation*}
<br>
## Normalization
\begin{equation*}
\mathbf{x}_i\_new\ = \frac{\mathbf{x}_i-mean(x)}{max(x)-min(x)}
\end{equation*}
<br>
#### sklearn에서 제공하는 Normalizer 모듈과 일반적인 정규화는 약간의 차이가 있다. <br>
#### 선형대수에서의 정규화 개념이 적용됐다.
