In [6]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [2]:
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN ],
              [np.NaN, 5, np.NaN, 3, 1 ],
              [np.NaN, np.NaN, 3, 4, 4 ],
              [5, 2, 1, 2, np.NaN ]])
num_users, num_items = R.shape
K=3

In [3]:
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [7]:
def get_rmse(R, P, Q, non_zeros):
    error = 0
    full_pred_matrix = np.dot(P, Q.T)
    
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

In [10]:
non_zeros = [ (i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0]

steps = 1000
learning_rate = 0.01
r_lambda = 0.01

for step in range(steps):
    for i, j, r in non_zeros:
        eij = r - np.dot(P[i, :], Q[j, :].T)
        P[i, :] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda * P[i, :])
        Q[j, :] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda * Q[j, :])
    
    rmse = get_rmse(R, P, Q, non_zeros)
    if (step % 50) == 0:
        print("### iteration step : ", step, "rmse : ", rmse)

### iteration step :  0 rmse :  3.2388050277987723
### iteration step :  50 rmse :  0.48767231013696477
### iteration step :  100 rmse :  0.1564340384819248
### iteration step :  150 rmse :  0.07455141311978032
### iteration step :  200 rmse :  0.0432522679857931
### iteration step :  250 rmse :  0.029248328780879088
### iteration step :  300 rmse :  0.022621116143829344
### iteration step :  350 rmse :  0.01949363619652533
### iteration step :  400 rmse :  0.018022719092132503
### iteration step :  450 rmse :  0.01731968595344277
### iteration step :  500 rmse :  0.01697365788757103
### iteration step :  550 rmse :  0.016796804595895533
### iteration step :  600 rmse :  0.01670132290188455
### iteration step :  650 rmse :  0.016644736912476654
### iteration step :  700 rmse :  0.016605910068210192
### iteration step :  750 rmse :  0.01657420047570466
### iteration step :  800 rmse :  0.016544315829215932
### iteration step :  850 rmse :  0.01651375177473506
### iteration step :  900 r

In [11]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬: \n', np.round(pred_matrix, 3))

예측 행렬: 
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]
